# import required libraries
from snakemake.utils import min_version


##### set minimum snakemake version #####
min_version("8.4.1")


# ***** Transfer marginal GWAS results to MVP *****
# 1. Subset gwas for a given seqid_locus pair
#   - save also variants list for later genotype extraction
# 2. Lift positions in GWAS to GRCh38
#   - save SNPs in the region in a VCF file
#   - execute genomic liftover using bcftools plugin
#   - save lifted positions in TXT format
# 3. Compute allele frequencies (AFs) from INTERVAL genotypes
#   - use variants list to extract AF for variants in the region 
# 4. Reframe sumstat in a MVP-requested structure
#   - merge all files including AFs, lifted positions with the extracted regions


# read the configuration file
configfile: "conf/config.yaml"
config_copy = "conf/config.yaml"


include: "rules/common.smk"
include: "rules/subset_gwas.smk"
include: "rules/run_liftover.smk"
include: "rules/recompute_freq.smk"
include: "rules/reformat_gwas.smk"
include: "rules/combine_reports.smk"
include: "rules/return_config.smk"



rule all:
    input:
        #expand(ws_path("report/{locuseq}.report"), locuseq = my_lb.locuseq),
        rules.combine_reports.output.combined
