path_geno: "/scratch/gianmauro.cuccuru/genomics_QC_pipeline/results_interval/pgen/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"
path_gwas: "/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped_filtered/output/"
loci_file: "/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/bonferroni_threshold/subset_for_coloc.txt"
workspace_path: "results/issue_40"

# Files related to genomic lift-over
chain_37to38: "/group/diangelantonio/public_data/liftOver/hg19ToHg38.over.chain.gz"
chain_38to37: "/group/diangelantonio/public_data/liftOver/hg38ToHg19.over.chain.gz"
fasta_hg37: "/group/diangelantonio/public_data/liftOver/human_g1k_v37.fasta"
fasta_hg38: "/group/diangelantonio/public_data/liftOver/hg38.fa"
start_build: "GRCh37" # GRCh37 or GRCh38
target_build: "GRCh38"

constants:
  sample_size: 13445
