executor: slurm
jobs: 450
software-deployment-method:
   - conda
#   - apptainer
retries: 3

# Cluster submission
jobname: "{jobid}.{rule}"
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 2
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
slurm-keep-successful-logs: True

default-resources:
    slurm_partition: cpuq
    #slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5

set-resources:
    subset_gwas:
        mem_mb: 512 + attempt * 1024
        threads: *cores
    convert_to_vcf:
        mem_mb: 512 + attempt * 1024
    liftover_vcf:
        mem_mb: 512 + attempt * 512
        threads: *cores
    compute_maf:
        mem_mb: 2048 + attempt * 1024
        threads: *cores
    reformat_sumstat:
        mem_mb: 512 + attempt * 1024
    combine_reports:
        mem_mb: 512 + attempt * 1024
